In [ ]:
import numpy as np 
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder,LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.linear_model  import LogisticRegression

recommended_material

3 High School : 
Harvard Online Courses - https://online-learning.harvard.edu/, Stanford Online - https://online.stanford.edu/, Coursera Courses - https://www.coursera.org/                     1652

2 Kindergarten:
PBS Kids Learning Games - https://pbskids.org/, Sesame Street Learning - https://www.sesamestreet.org/, National Geographic Kids - https://kids.nationalgeographic.com/         1613


1 Middle School:
CK-12 Interactive Learning - https://www.ck12.org/, NASA STEM Engagement - https://www.nasa.gov/stem/, Quizlet Study Sets - https://quizlet.com/                                1599

0   Elemenrary : 
Adventure Academy - https://www.adventureacademy.com/, Scholastic Learn at Home - https://classroommagazines.scholastic.com/, CoolMath4Kids - https://www.coolmath4kids.com/    1579

In [2]:
dataset = pd.read_csv(r"k-12.csv")
dataset.sample(10)

,Name,Age,Gender,Country,State,City,Parental_Education_Level,Earning Class,Level,Course Name,Course Level,Material Level,Previous_Scores,Assesment Score,IQ,Attendance,Material Name,recommended_material,Study Time,promoted
903,Heidi Evans,10,Female,Mali,Mississippi,Port Anthony,High School,Medium,Elementary,"Stories of the Past, Art and Imagination, Disc...",Medium,Medium,61,68,88.65,86,"Textbooks, Workbooks, Educational Apps, Scienc...",Adventure Academy - https://www.adventureacade...,4.08,No
1143,Shirley Patterson,16,Female,Moldova,Wyoming,Brianville,High School,High,High School,"Economics, Psychology, Algebra II",Medium,Medium,78,65,93.60,74,"Advanced Textbooks, Research Papers, Online Ce...",Harvard Online Courses - https://online-learni...,3.90,No
2480,William Saunders,10,Male,French Polynesia,Louisiana,North Timothy,College,Medium,Elementary,"Building Math Foundations, Discovering Nature ...",Medium,Medium,63,68,89.55,91,"Textbooks, Workbooks, Educational Apps, Scienc...",Adventure Academy - https://www.adventureacade...,4.08,No
3598,Travis Fitzgerald,14,Female,Chad,Idaho,New Travis,College,High,High School,"Chemistry, Geometry, Career Planning",Medium,Medium,67,68,91.35,76,"Advanced Textbooks, Research Papers, Online Ce...",Harvard Online Courses - https://online-learni...,4.08,No
664,Patrick Johnson,5,Female,Cambodia,North Carolina,Walshside,High School,Low,Kindergarten,"Play and Learn, Exploring the World, Fun with ...",Medium,Medium,51,62,78.75,61,"Storybooks, Flashcards, Interactive Games, Col...",PBS Kids Learning Games - https://pbskids.org/...,3.72,No
4287,Nicole Vasquez,16,Female,Egypt,Kansas,New Daisy,Postgraduate,Low,High School,"Physics, Economics, Business Studies",Medium,Low,70,68,92.70,90,"Advanced Textbooks, Research Papers, Online Ce...",Harvard Online Courses - https://online-learni...,4.08,No
367,Tina Clark,9,Female,Indonesia,Montana,Lake Coreyfurt,College,Low,Elementary,"Sports and Games, Stories of the Past, Buildin...",Medium,High,90,67,100.80,80,"Textbooks, Workbooks, Educational Apps, Scienc...",Adventure Academy - https://www.adventureacade...,4.02,No
4011,Michelle Perry,16,Male,Costa Rica,North Carolina,Reneehaven,Postgraduate,Medium,High School,"Cultural and Political Geography, SAT/ACT Prep...",Medium,High,82,71,100.80,82,"Advanced Textbooks, Research Papers, Online Ce...",Harvard Online Courses - https://online-learni...,4.26,Yes
2045,Brittney Smith,12,Female,Saint Kitts and Nevis,Maine,Churchside,High School,Medium,Middle School,"Instruments and Composition, World History, Co...",Medium,Medium,92,65,99.90,85,"Reference Books, Online Courses, Project Kits,...",CK-12 Interactive Learning - https://www.ck12....,3.90,No
5249,Sonia Brewer,5,Male,Guinea,Idaho,East Stevenstad,College,High,Kindergarten,"My Family and Community, Numbers Around Us, Pl...",Medium,Medium,52,73,89.10,92,"Storybooks, Flashcards, Interactive Games, Col...",PBS Kids Learning Games - https://pbskids.org/...,4.38,No

In [3]:
dataset = dataset.drop(columns=['Name','Gender','Country','State','City','Parental_Education_Level','Earning Class','Course Name','Material Name','promoted'])

In [4]:
x = dataset.drop(columns=['recommended_material'])
y = dataset['recommended_material']

In [5]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [6]:
x

,Age,Level,Course Level,Material Level,Previous_Scores,Assesment Score,IQ,Attendance,Study Time
0,10,Elementary,Medium,High,73,67,93.15,84,4.02
1,11,Middle School,Medium,Medium,59,61,81.45,64,3.66
2,5,Kindergarten,Medium,Medium,91,74,107.55,98,4.44
3,15,High School,Medium,Medium,98,71,108.00,89,4.26
4,10,Elementary,High,Medium,65,70,92.25,92,4.20
...,...,...,...,...,...,...,...,...,...
6438,18,High School,Medium,Medium,76,68,95.40,69,4.08
6439,5,Kindergarten,High,Medium,81,69,98.55,76,4.14
6440,10,Elementary,Medium,Low,65,68,90.45,90,4.08
6441,5,Kindergarten,Medium,High,91,68,102.15,86,4.08
6442,5,Kindergarten,Medium,Low,94,64,99.90,67,3.84

In [7]:
lb = LabelEncoder()

y_train = lb.fit_transform(y_train)
y_test = lb.transform(y_test)

In [8]:
transformer1 = ColumnTransformer(
    transformers=[
        ('tf1', OrdinalEncoder(categories=[
              # Categories for 'Earning Class'
            ['Kindergarten', 'Elementary', 'Middle School', 'High School'],  # Categories for 'Level'
            ['Low', 'Medium', 'High'],  # Categories for 'Course Level'
            ['Low', 'Medium', 'High']  # Categories for 'Material Level'
        ]), [ 'Level', 'Course Level', 'Material Level'])  # Ordinal columns
    ],
    remainder='passthrough'
)

pipeline = Pipeline(
    [
        ('Preprocess',transformer1),
        ('Scaling',StandardScaler()),
        ('SoftMax',LogisticRegression(multi_class='multinomial'))
    ]
)

In [9]:
pipeline.fit(x_train,y_train)

c:\Users\marut\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\marut\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\compose\_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('Preprocess',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('tf1',
                                                  OrdinalEncoder(categories=[['Kindergarten',
                                                                              'Elementary',
                                                                              'Middle '
                                                                              'School',
                                                                              'High '
                                                                              'School'],
                                                                             ['Low',
                                                                              'Medium',
                                                                              'High'],
                                                                             ['Low',
                                                                              'Medium',
                                                                              'High']]),
                                                  ['Level', 'Course Level',
                                                   'Material Level'])])),
                ('Scaling', StandardScaler()),
                ('SoftMax', LogisticRegression(multi_class='multinomial'))])

In [10]:
y_pred = pipeline.predict(x_test)

In [11]:
accuracy_score(y_test,y_pred)

1.0

In [12]:
confusion_matrix(y_test,y_pred)

array([[315,   0,   0,   0],
       [  0, 337,   0,   0],
       [  0,   0, 344,   0],
       [  0,   0,   0, 293]])

In [13]:
# Recommend material as per student level
input_data = pd.DataFrame([[
    6,	'Kindergarten',	'Medium',	'Medium',	89,	69,	102.15,	86,	4.14
]], columns=x_train.columns)

# Make prediction
prediction = pipeline.predict(input_data)

def recommend(n):
    if n==0:
        print(y[0])
    elif n==1:
        print(y[1])
    elif n==2:
        print(y[3])
    else:
        print(y[2])            

print("Kindly Follow These Resources : ")        
recommend(prediction[0])

Kindly Follow These Resources :
PBS Kids Learning Games - https://pbskids.org/, Sesame Street Learning - https://www.sesamestreet.org/, National Geographic Kids - https://kids.nationalgeographic.com/

In [14]:
y[2]

'PBS Kids Learning Games - https://pbskids.org/, Sesame Street Learning - https://www.sesamestreet.org/, National Geographic Kids - https://kids.nationalgeographic.com/'

In [15]:
dataset['recommended_material'].value_counts()

recommended_material
Harvard Online Courses - https://online-learning.harvard.edu/, Stanford Online - https://online.stanford.edu/, Coursera Courses - https://www.coursera.org/                     1652
PBS Kids Learning Games - https://pbskids.org/, Sesame Street Learning - https://www.sesamestreet.org/, National Geographic Kids - https://kids.nationalgeographic.com/         1613
CK-12 Interactive Learning - https://www.ck12.org/, NASA STEM Engagement - https://www.nasa.gov/stem/, Quizlet Study Sets - https://quizlet.com/                                1599
Adventure Academy - https://www.adventureacademy.com/, Scholastic Learn at Home - https://classroommagazines.scholastic.com/, CoolMath4Kids - https://www.coolmath4kids.com/    1579
Name: count, dtype: int64

In [16]:
# import pickle
# pickle.dump(pipeline,open('recomendation.pkl','wb'))